### ISSUE TITLE
Terminal not opening in Windows

### ISSUE THREAD

**Issue by scottbusche-usps** [freelensapp/freelens#1228]
### Describe the bug

Opening a terminal window displays, `Connecting...` forever.

### Reproduction steps

Navigate to a cluster and open a terminal window.

### Expected behavior

The terminal window connects to the cluster.

### Screenshots

<img width="337" height="154" alt="Image" src="https://github.com/user-attachments/assets/65b353a8-42d4-45ce-a60a-217a353c6caf" />

### Freelens version

1.6.0, this worked fine on 1.5.3 and is a regression.

### Operating system type and version

Windows 11

### Installation method

MSI

### Kubernetes cluster version used with Freelens

Tried against 1.30 and 1.32

### Logs

Logs:
```
error: [SHELL-SESSION]: failed to open a local shell The specified procedure could not be found.
\\?\C:\Users\moo\AppData\Local\Temp\31222249-f856-4dce-8305-adb7cf9760aa.tmp.node {"code":"ERR_DLOPEN_FAILED","stack":"Error: The specified procedure could not be found.\r\n\\\\?\\C:\\Users\\moo\\AppData\\Local\\Temp\\31222249-f856-4dce-8305-adb7cf9760aa.tmp.node\n    at process.func [as dlopen] (node:electron/js2c/node_init:2:2569)\n    at Module._extensions..node (node:internal/modules/cjs/loader:1930:18)\n    at Object.func [as .node] (node:electron/js2c/node_init:2:2796)\n    at Module.load (node:internal/modules/cjs/loader:1472:32)\n    at Module._load (node:internal/modules/cjs/loader:1289:12)\n    at c._load (node:electron/js2c/node_init:2:17950)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)\n    at Module.require (node:internal/modules/cjs/loader:1494:12)\n    at require (node:internal/modules/helpers:135:16)"}
```

### Kubeconfig

N/A

**Comment by avatin-powens** [comment]
Same problem here, maybe full stack trace could be useful:

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- C:\Users\****\AppData\Local\Programs\freelens\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js
- C:\Users\****\AppData\Local\Programs\freelens\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js
- C:\Users\****\AppData\Local\Programs\freelens\resources\app.asar\node_modules\node-pty\lib\index.js
- C:\Users\****\AppData\Local\Programs\freelens\resources\app.asar\node_modules\@freelensapp\core\static\build\library\main.js
- C:\Users\****\AppData\Local\Programs\freelens\resources\app.asar\static\build\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:1408:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129227)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1064:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1069:22)
    at Module._load (node:internal/modules/cjs/loader:1218:37)
    at c._load (node:electron/js2c/node_init:2:17950)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1494:12)
    at require (node:internal/modules/helpers:135:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\****\\AppData\\Local\\Programs\\freelens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsPtyAgent.js',
    'C:\\Users\\****\\AppData\\Local\\Programs\\freelens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsTerminal.js',
    'C:\\Users\\****\\AppData\\Local\\Programs\\freelens\\resources\\app.asar\\node_modules\\node-pty\\lib\\index.js',
    'C:\\Users\\****\\AppData\\Local\\Programs\\freelens\\resources\\app.asar\\node_modules\\@freelensapp\\core\\static\\build\\library\\main.js',
    'C:\\Users\\****\\AppData\\Local\\Programs\\freelens\\resources\\app.asar\\static\\build\\main.js',
    undefined
  ]
}

error:   ┏ [SHELL-SESSION]: failed to open a local shell The specified module could not be found.
\\?\C:\Users\****\AppData\Local\Temp\****.tmp.node +6s
error:   ┃ [ 1] Error: The specified module could not be found.
error:   ┃ [ 2] \\?\C:\Users\****\AppData\Local\Temp\****.tmp.node
error:   ┃ [ 3]     at process.func [as dlopen] (node:electron/js2c/node_init:2:2569)
error:   ┃ [ 4]     at Module._extensions..node (node:internal/modules/cjs/loader:1930:18)
error:   ┃ [ 5]     at Object.func [as .node] (node:electron/js2c/node_init:2:2796)
error:   ┃ [ 6]     at Module.load (node:internal/modules/cjs/loader:1472:32)
error:   ┃ [ 7]     at Module._load (node:internal/modules/cjs/loader:1289:12)
error:   ┃ [ 8]     at c._load (node:electron/js2c/node_init:2:17950)
error:   ┃ [ 9]     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
error:   ┃ [10]     at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
error:   ┃ [11]     at Module.require (node:internal/modules/cjs/loader:1494:12)
error:   ┃ [12]     at require (node:internal/modules/helpers:135:16)
error:   ┗ [13] { code: 'ERR_DLOPEN_FAILED', timestamp: '24/09/2025 19:15:11' }
```

**Comment by dex4er** [comment]
I don't see any obvious error besides maybe sideffect of https://github.com/freelensapp/freelens/pull/1117 

I don't have a Windows machine to build (x86) as I'm using only arm64, so my possibilities to troubleshoot it are limited. Can anybody help with this regression? 

This command should help with checking if pty.node (or any other file) is in asar:

```pwsh
pnpm asar l C:\Users\dex4er\AppData\Local\Programs\freelens\resources\app.asar | Select-String "pty"
```

v1.6.0 output:

```text
\node_modules\node-pty\build\Release\obj\conpty\conpty.node.recipe
\node_modules\node-pty\build\Release\obj\pty\pty.node.recipe
\node_modules\node-pty\build\Release\conpty.node
\node_modules\node-pty\build\Release\pty.node
\node_modules\node-pty\bin\win32-arm64-133\node-pty.node
```

v1.5.3 output:

```text
\node_modules\node-pty\build\Release\obj\conpty\conpty.node.recipe
\node_modules\node-pty\build\Release\obj\pty\pty.node.recipe
\node_modules\node-pty\build\Release\conpty.node
\node_modules\node-pty\build\Release\pty.node
\node_modules\node-pty\bin\win32-arm64-133\node-pty.node
```

so I guess it is not about missing binary.

**Comment by scottbusche-usps** [comment]
I am on x86, what directory do you want the `pnpm` command ran from? It needs to have a `package.json` to work and I don't see one anywhere along that path.

**Comment by scottbusche-usps** [comment]
It seems like the error is that it's looking in the `Debug` folder instead of `Release`, no?

**Comment by dex4er** [comment]
No idea why library now tries anything in Debug folder. I don't see this stacktrace on my Windows (arm64) so I can't confirm it, except that terminal doesn't start.

**Comment by avatin-powens** [comment]
I started FreeLens with PowerShell to have the logging in the console.

To be honest, I tried to fix the issue with changing settings. Hope I didn't add this error doing that.

**Comment by dex4er** [comment]
downgrading node-gyp didn't help so I'm going to check if electron itself could be a reason

**Comment by dex4er** [comment]
The main reason of broken Windows version is that we use `@actions/node` that breaks if pnpm or yarn is used. See https://github.com/actions/setup-node/issues/1357 for details. Unfortunately, nobody noticed the problem because `engineStrict` option in pnpm is false by default.

So now we'll have fixes for `@actions/node` v5: disabled cache for this action and `@actions/cache` is used explicitely again.

PNPM has `engineStrict` enabled again.

Windows is not fully tested as we need to run Kubernetes for integration tests. Theoretically, KinD might work as we migrated from minikube.

**Comment by robertobandini** [comment]
However, we want to prevent these situations by:

- Checkbox in the discussion for each upcoming release regarding testing on at least three OSes by a tester, for tests that cannot be automated or have not yet been automated.
- If possible, the tester should be a volunteer who uses Freelens with a given OS regularly in their day-to-day work.
- Consider defining a standard testing procedure, i.e., regarding which use cases or situations to test.

Let us know what you think, and we can start a discussion and poll about it.
I think the important thing is to try to prevent regressions as much as possible by simply waiting for someone to test before releasing.

FYI @mariomamo @leo-capvano

**Comment by dex4er** [comment]
There is something in the logs. 

In the past Integration Tests log for "Build Electron App" shown signing OpenConsole.exe

```
  • updating asar integrity executable resource  executablePath=dist\win-unpacked\Freelens.exe
  • signing with signtool.exe  path=dist\win-unpacked\Freelens.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\pnpm\dist\vendor\fastlist-0.3.0-x64.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\pnpm\dist\vendor\fastlist-0.3.0-x86.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\node-pty\third_party\conpty\1.22.250204002\win10-x64\OpenConsole.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\node-pty\third_party\conpty\1.22.250204002\win10-arm64\OpenConsole.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\node-pty\build\Release\winpty-agent.exe
  • signing with signtool.exe  path=dist\win-unpacked\resources\app.asar.unpacked\node_modules\node-pty\build\Release\conpty\OpenConsole.exe
```

Recently it is missing:

```
  • signing with signtool.exe  path=dist\win-unpacked\Freelens.exe
```

**Comment by dex4er** [comment]
Probably this security fix broke it for Windows: https://github.com/freelensapp/freelens/pull/1213

**Comment by dex4er** [comment]
Reopened until it is finally confirmed that the issue is fixed.

**Comment by scottbusche-usps** [comment]
Do you have a new binary/installer to test with?

**Comment by dex4er** [comment]
@scottbusche-usps https://github.com/freelensapp/freelens-nightly-builds/releases/tag/v1.6.1-0-nightly-2025-09-25
